version:  '3'

services:
  app:
    build: .
    container_name: orel-app
    ports:
      - 3000:3000
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_NAME=orel-docker
      - DB_HOSTNAME=mysql
    command: npm run docker
    volumes:
      - .:/user/src/app
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.27
    container_name: orel-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: --character-set-server=utf8
    restart: always
    volumes:
      - db:/var/lib/mysql

volumes:
  db: